### ISSUE TITLE
求一个代码

### ISSUE THREAD

**Issue by AneonCode** [xjblszyy/JiuJia#1]
求一个脚本兄弟

**Comment by FengGuanxi** [comment]
求代码

**Comment by xjblszyy** [comment]
我已经写完了，正在本地跑测试，需要几轮测试它能正常运转了我再上传上去

**Comment by AneonCode** [comment]
> 我已经写完了，正在本地跑测试，需要几轮测试它能正常运转了我再上传上去

我可以和你一起维护，方便加个Q或者V交流一下吗？

**Comment by xjblszyy** [comment]
> > 我已经写完了，正在本地跑测试，需要几轮测试它能正常运转了我再上传上去
> 
> 我可以和你一起维护，方便加个Q或者V交流一下吗？

xjblsz@163.com 发个邮件过来吧，我单独发给你，刚好我需要一起能交流一下的人，我现在发现了其他问题，没有攻破

**Comment by xjblszyy** [comment]
15652912563 vx







在 2020-07-14 11:27:17，"董昱灿" <notifications@github.com> 写道：

我已经写完了，正在本地跑测试，需要几轮测试它能正常运转了我再上传上去

我可以和你一起维护，方便加个Q或者V交流一下吗？

**Comment by AneonCode** [comment]
加了，同意下，谢谢

**Comment by zinczeng** [comment]
求源码
