### ISSUE TITLE
能一起研究下么，现在九价群买个资格都1800了。救急啊

### ISSUE THREAD

**Issue by weishunjie-github** [xjblszyy/JiuJia#11]

**Comment by xjblszyy** [comment]
自己看吧

**Comment by weishunjie-github** [comment]
okay，感谢。希望你早日脱单~，祝福你


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xjblszyy/JiuJia"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月26日(星期一) 下午3:56
收件人:&nbsp;"xjblszyy/JiuJia"<JiuJia@noreply.github.com&gt;;
抄送:&nbsp;"魏舜杰"<157680333@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [xjblszyy/JiuJia] 能一起研究下么，现在九价群买个资格都1800了。救急啊 (#11)





 
自己看吧
