### ISSUE TITLE
请问一下验证码你是用什么方式解决的？

### ISSUE THREAD

**Issue by zinczeng** [xjblszyy/JiuJia#2]
如题

**Comment by xjblszyy** [comment]
http://www.jianjiaoshuju.com/goods/29793501BF479FD6F01367EE0AA8DDD1.html

**Comment by xjblszyy** [comment]
> 如题

http://www.jianjiaoshuju.com/goods/29793501BF479FD6F01367EE0AA8DDD1.html

**Comment by zinczeng** [comment]
老哥稳

**Comment by xjblszyy** [comment]
这个打码有点不稳定，准备上机器学习了，你有这方面经验的话可以交流一下了～

**Comment by zinczeng** [comment]
老哥，机器学习的如何了？另外九价的秒杀好像没了。

**Comment by xjblszyy** [comment]
> 老哥，机器学习的如何了？另外九价的秒杀好像没了。

它换成小程序了，而且没验证码了，这几天还得抓包一下看接口，又得重新适配了才行，唉，好难

**Comment by zinczeng** [comment]
那机器学习打码岂不是白学习了，我刚刚尝试fiddler抓包一下，发现桌面版的微信打不开秒苗的小程序，不知道是不是做了限制，对小程序了解不多

> > 老哥，机器学习的如何了？另外九价的秒杀好像没了。
> 
> 它换成小程序了，而且没验证码了，这几天还得抓包一下看接口，又得重新适应了才行，唉，好难

那机器学习打码岂不是白学习了，我刚刚尝试fiddler抓包一下，发现桌面版的微信打不开秒苗的小程序，不知道是不是做了限制，对小程序了解不多

**Comment by xjblszyy** [comment]
> 那机器学习打码岂不是白学习了，我刚刚尝试fiddler抓包一下，发现桌面版的微信打不开秒苗的小程序，不知道是不是做了限制，对小程序了解不多
> 
> > > 老哥，机器学习的如何了？另外九价的秒杀好像没了。
> > 
> > 
> > 它换成小程序了，而且没验证码了，这几天还得抓包一下看接口，又得重新适应了才行，唉，好难
> 
> 那机器学习打码岂不是白学习了，我刚刚尝试fiddler抓包一下，发现桌面版的微信打不开秒苗的小程序，不知道是不是做了限制，对小程序了解不多

我还没弄明白机器学习打码，哈哈哈，所以还没弄，今天早上有抢购，我抓包了，结果秒无，抓不出来后续的接口数据，没办法，只能等明天的了

**Comment by zinczeng** [comment]
昨天试着抓了一下包，进入秒杀页面就被抢光了，接口都没有解析到，你有解析到秒苗流程所需的接口吗
