### ISSUE TITLE
请问下怎么看不到代码，我抢了很多次了，快绝望了

### ISSUE THREAD

**Issue by lzming1989** [xjblszyy/JiuJia#3]

**Comment by xjblszyy** [comment]
再稍等2周吧，代码其实已经差不多了，但是验证码有点头疼，现在的用法是调用远程接口去打码的，后来发现只有600多个图片就全部爬下来了，前几天发现加到了5000多张了，所以准备上机器学习去打这个验证码，如果你有这方面经验可以交流一下
